
[project]
name = "llms"
version = "0.1.0"
requires-python = ">=3.10"


# Runtime dependencies
dependencies = [
    "langchain-community",
    "langchain-core",
    "langchain-chroma",
    "langchain-ollama",
    "langchain==0.3.0",
    "langchain-text-splitters",
    "langgraph-checkpoint-postgres",
    "psycopg-binary",
    "tqdm",
    "seaborn",

    "dotenv",
    "pypdf",
    "ruff",
    "ollama",
    "bs4",
    "typer",
    # translate_audio
    "pytubefix",
    "google-genai",
    "docarray",
    # multimodel chat
    "unstructured[all-docs]",
    "pillow", 
    "lxml",
    "chromadb",
    "tiktoken",
    "langchain-groq",

    #google adk
    "gcloud",
    "langgraph",
    "google-cloud-aiplatform",
    "langchain-google-genai",
    "google-adk",
    "deprecated",

    # crew ai
    "crewai",

    "datasets",
    "ragas==0.4.3",

    "rich",
    "unsloth",
    "bitsandbytes", # need for unsloth
    "xformers",
    "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo",
    "unsloth[base] @ git+https://github.com/unslothai/unsloth",
    "torch>=2.8.0",
    "triton>=3.4.0"
]

[tool.pyright]
include = ["src"]
exclude = [
    "small_rag_dataset/",
    "*_db/",
    "*.sql"
]
